#!/usr/bin/env bash
# Displays information about subdomains

# Function retreive end display subdomain informations
domain_information() {
	local valid_subdomains=("www" "lb-01" "web-01" "web-02")

	if [[ " ${valid_subdomains[@]} " =~ " $2 " ]]; then
		line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
		echo "$2" "$line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
	fi
}

if [ "$#" == 1 ]
then
	domain_information "$1" "www"
	domain_information "$1" "lb-01"
	domain_information "$1" "web-01"
	domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
	domain_information "$1" "$2"
fi
