#!/usr/bin/env bash
# redirecting to another page
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello world!" > sudo /var/www/html/index.nginx-debian.html
sudo sed -i '/^[[:space:]]*server {/!d; /^[[:space:]]*server {/a\
\    location \/redirect_me {\
\        rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\
\    }' /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx start
