#!/usr/bin/env bash
#Configuring HAproxy

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get -y install haproxy=2.8.\*
content="\n\tbind :80\n\tmode http\n\tuse_backend nizar_backend\nbackend nizar_backend\n\tbalance roundrobin\n\tserver 366391-web-01 18.210.14.235:80 check\n\tserver 366391-web-02 100.25.16.27:80 check"
sudo sed -i "/errorfile 504/a\\
frontend myconf" /etc/haproxy/haproxy.cfg
sudo sed -i "/frontend myconf/a\\
$content" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
