#!/usr/bin/env bash
#Configuring HAproxy

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get -y install haproxy=2.8.\*
content="\n\tbind :80\n\tmode http\n\tuse_backend nizar_backend\nbackend nizar_backend\n\tbalance roundrobin\n\tserver 366391-web-01 54.90.39.55:80 check\n\tserver 366391-web-02 54.175.58.218:80 check"
sudo sed -i '/errorfile 504/a frontend myconf' /etc/haproxy/haproxy.cfg
sudo sed -i "s/frontend myconf/&$content/g" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
