#!/usr/bin/env bash
# Debugging server with a problem on listening on prt 80
sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sudo service nginx restart
