#!/usr/bin/env bash
# Debugging server with a problem on listening on prt 80
sudo apt-get install nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
