#!/usr/bin/env bash
#manage manage_my_process process
case "$1" in
	start)
		./manage_my_process start &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		kill -9 "$(/var/run/my_process.pid)"
		rm /var/run/my_process.pid
		echo "manage_my_process stoped"
		;;
	restart)
		kill -9 "$(/var/run/my_process.pid)"
		rm /var/run/my_process.pid
		./manage_my_process start &
                echo $! > /var/run/my_process.pid
                echo "manage_my_process restarted"
                ;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
