#!/usr/bin/env bash
#displays the content of the file /etc/passwd
while IFS=: read -r username password userid grid useridinfo home command; do
	echo "The user $username is part of the $grid gang, lives in $home and rides $command. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < /etc/passwd
