#!/usr/bin/env bash
# Advanced Connect to nginx as nginx user and lestening on port 8080
sed -i "s/#user .*/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
